# Generated by Django 5.0.6 on 2026-09-25 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('session_key', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=25)),
                ('shipping_address', models.TextField()),
                ('city', models.CharField(default='New York', max_length=100)),
                ('postal_code', models.CharField(default='10001', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('COD', 'Cash on Express Delivery'), ('CARD', 'Credit / Debit Card (Online)'), ('APPLE_PAY', 'Apple Pay / Google Pay'), ('INSURANCE', 'Health Insurance Co-Pay')], default='COD', max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Payment Pending'), ('PAID', 'Payment Completed'), ('REFUNDED', 'Refunded'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('order_status', models.CharField(choices=[('PLACED', 'Order Placed & Received'), ('PRESCRIPTION_VERIFICATION', 'Rx Prescription Under Pharmacist Review'), ('PROCESSING', 'Pharmacist Dispensing & Quality Check'), ('PACKED', 'Temperature-Controlled Packaged'), ('OUT_FOR_DELIVERY', 'Out for Express Courier Delivery'), ('DELIVERED', 'Delivered to Doorstep'), ('CANCELLED', 'Order Cancelled')], default='PLACED', max_length=30)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('estimated_delivery', models.CharField(default='Same-Day Express (Within 2 Hours)', max_length=100)),
                ('delivery_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PLACED', 'Order Placed & Received'), ('PRESCRIPTION_VERIFICATION', 'Rx Prescription Under Pharmacist Review'), ('PROCESSING', 'Pharmacist Dispensing & Quality Check'), ('PACKED', 'Temperature-Controlled Packaged'), ('OUT_FOR_DELIVERY', 'Out for Express Courier Delivery'), ('DELIVERED', 'Delivered to Doorstep'), ('CANCELLED', 'Order Cancelled')], max_length=30)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=150)),
                ('patient_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=150, null=True)),
                ('clinic_hospital', models.CharField(blank=True, max_length=200, null=True)),
                ('prescription_file', models.FileField(upload_to='prescriptions/%Y/%m/')),
                ('notes', models.TextField(blank=True, help_text='Patient symptoms or specific medication instructions', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Pharmacist Review'), ('VERIFIED', 'Verified by Clinical Pharmacist'), ('REJECTED', 'Requires Doctor Clarification / Rejected'), ('DISPENSED', 'Medication Dispensed')], default='PENDING', max_length=20)),
                ('pharmacist_notes', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.prescription'),
        ),
    ]
