# Generated by Django 5.0.6 on 2026-09-25 18:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('title', models.CharField(default='PharmD, Lead Clinical Pharmacist', max_length=100)),
                ('specialty', models.CharField(choices=[('CLINICAL_PHARMACIST', 'Lead Clinical Pharmacist (PharmD)'), ('GENERAL_PHYSICIAN', 'General Physician & Family Medicine'), ('PEDIATRICIAN', 'Pediatrics & Child Health Specialist'), ('DERMATOLOGIST', 'Dermatology & Cosmetology'), ('CARDIOLOGIST', 'Cardiology & Hypertension Specialist'), ('NUTRITIONIST', 'Clinical Dietitian & Nutritionist'), ('ENDOCRINOLOGIST', 'Endocrinology & Diabetes Specialist')], default='CLINICAL_PHARMACIST', max_length=40)),
                ('license_number', models.CharField(default='LIC-US-98432', max_length=50)),
                ('qualification', models.CharField(default='PharmD, Board Certified Pharmacotherapy Specialist', max_length=200)),
                ('experience_years', models.PositiveIntegerField(default=10)),
                ('bio', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='0 for Free Triage', max_digits=8)),
                ('rating', models.DecimalField(decimal_places=2, default=4.95, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('reviews_count', models.PositiveIntegerField(default=140)),
                ('is_available_online', models.BooleanField(default=True)),
                ('next_available_slot', models.CharField(default='Today at 2:30 PM', max_length=100)),
                ('languages_spoken', models.CharField(default='English, Spanish', max_length=200)),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', '-rating'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=150)),
                ('patient_email', models.EmailField(max_length=254)),
                ('patient_phone', models.CharField(max_length=30)),
                ('patient_age', models.PositiveIntegerField(default=30)),
                ('patient_gender', models.CharField(default='Not Specified', max_length=20)),
                ('preferred_date', models.DateField()),
                ('preferred_time_slot', models.CharField(max_length=50)),
                ('consultation_type', models.CharField(choices=[('VIDEO', 'High-Definition Video Call'), ('AUDIO', 'Direct Phone Call'), ('CHAT', 'Encrypted Instant Chat'), ('IN_PERSON', 'In-Clinic Priority Appointment')], default='VIDEO', max_length=20)),
                ('symptoms', models.TextField(help_text='Describe primary health symptoms or medication questions')),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('prescription_attachment', models.FileField(blank=True, null=True, upload_to='consultations/rx/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Doctor Confirmation'), ('CONFIRMED', 'Confirmed & Slot Reserved'), ('IN_PROGRESS', 'Consultation Live'), ('COMPLETED', 'Completed & Prescription Issued'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('meeting_link', models.URLField(blank=True, max_length=500, null=True)),
                ('doctor_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='telehealth.doctor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
