# Generated by Django 5.0.6 on 2026-09-26 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('facility_type', models.CharField(choices=[('PHARMACY', 'Antixor Certified Pharmacy & Store'), ('HOSPITAL', 'Partner Multi-Specialty Hospital'), ('EMERGENCY_CENTER', '24/7 Trauma & Emergency Center'), ('DIAGNOSTIC_LAB', 'Certified Diagnostic & Pathology Lab')], default='PHARMACY', max_length=30)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(default='New York', max_length=100)),
                ('state', models.CharField(default='NY', max_length=100)),
                ('postal_code', models.CharField(default='10001', max_length=20)),
                ('latitude', models.FloatField(default=40.7128)),
                ('longitude', models.FloatField(default=-74.006)),
                ('phone', models.CharField(max_length=30)),
                ('emergency_hotline', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_24_7', models.BooleanField(default=True)),
                ('ambulance_available', models.BooleanField(default=False)),
                ('available_beds', models.IntegerField(default=0, help_text='Applicable for hospitals')),
                ('rating', models.DecimalField(decimal_places=1, default=4.9, max_digits=3)),
                ('total_reviews', models.IntegerField(default=120)),
                ('services_offered', models.TextField(blank=True, help_text='Comma-separated: Cold-chain storage, ICU, 24/7 Dispensing, Lab Sampling', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='facilities/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Medical Facilities',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='chronic_conditions',
            field=models.TextField(blank=True, help_text='e.g. Type 2 Diabetes, Hypertension, Asthma', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='digital_health_id',
            field=models.CharField(blank=True, help_text='Unique Digital Health ID like ANT-P-882194', max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_phone',
            field=models.CharField(blank=True, help_text='Emergency Phone Number', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='blood_group',
            field=models.CharField(blank=True, default='O+', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='Contact Person Name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='medical_allergies',
            field=models.TextField(blank=True, help_text='e.g. Penicillin, Sulfa drugs, Aspirin', null=True),
        ),
        migrations.CreateModel(
            name='PatientIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=150)),
                ('patient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('patient_phone', models.CharField(max_length=30)),
                ('patient_age', models.IntegerField(default=28)),
                ('patient_gender', models.CharField(default='Female', max_length=20)),
                ('primary_symptom', models.CharField(default='Severe Headache & Low Fever', max_length=200)),
                ('symptoms_list', models.TextField(blank=True, help_text='Comma-separated symptoms selected by patient', null=True)),
                ('pain_severity', models.IntegerField(default=4, help_text='Scale from 1 (mild) to 10 (emergency)')),
                ('symptom_duration', models.CharField(default='2-3 Days', max_length=100)),
                ('prescription_attachment', models.FileField(blank=True, null=True, upload_to='intake_prescriptions/%Y/%m/')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Intake Submitted'), ('PHARMACIST_ALLOCATED', 'Assigned to Nearest Pharmacy'), ('CLINICAL_REVIEW', 'Clinical Pharmacist Reviewing'), ('PRESCRIPTION_APPROVED', 'Prescription & Dosage Approved'), ('DISPATCHED', 'Dispatched for 2-Hour Delivery'), ('COMPLETED', 'Completed')], default='SUBMITTED', max_length=30)),
                ('pharmacist_notes', models.TextField(blank=True, null=True)),
                ('safety_warning', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_intakes', to='core.medicalfacility')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intakes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientVital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic_bp', models.IntegerField(default=120, help_text='Systolic Blood Pressure (mmHg)')),
                ('diastolic_bp', models.IntegerField(default=80, help_text='Diastolic Blood Pressure (mmHg)')),
                ('blood_sugar', models.FloatField(default=95.0, help_text='Fasting Blood Sugar (mg/dL)')),
                ('heart_rate', models.IntegerField(default=72, help_text='Heart Rate (BPM)')),
                ('spo2', models.IntegerField(default=98, help_text='Oxygen Saturation (%)')),
                ('weight_kg', models.FloatField(default=68.5, help_text='Weight in KG')),
                ('bmi', models.FloatField(default=22.4, help_text='Body Mass Index')),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='PillReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=150)),
                ('dosage', models.CharField(default='1 Tablet after meal', max_length=50)),
                ('frequency', models.CharField(choices=[('MORNING', 'Morning (8:00 AM)'), ('AFTERNOON', 'Afternoon (1:00 PM)'), ('NIGHT', 'Night (9:00 PM)'), ('TWICE_DAILY', 'Twice Daily (Morning & Night)'), ('THRICE_DAILY', 'Thrice Daily')], default='MORNING', max_length=20)),
                ('time_slot', models.CharField(default='08:00 AM', max_length=50)),
                ('is_taken', models.BooleanField(default=False)),
                ('streak_days', models.IntegerField(default=5)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pill_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['time_slot', 'medicine_name'],
            },
        ),
    ]
