# Generated by Django 5.0.6 on 2026-09-25 18:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Article Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=270, unique=True)),
                ('excerpt', models.TextField(help_text='Brief summary for cards and meta description', max_length=400)),
                ('content', models.TextField(help_text='Full markdown or HTML content')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('cover_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('author_name', models.CharField(default='Dr. Marcus Vance', max_length=150)),
                ('author_title', models.CharField(default='Lead Clinical Pharmacologist', max_length=150)),
                ('author_avatar', models.URLField(blank=True, max_length=500, null=True)),
                ('medical_reviewer', models.CharField(default='Dr. Sophia Chen, MD (Board Certified)', max_length=150)),
                ('read_time_minutes', models.PositiveIntegerField(default=5)),
                ('tags', models.CharField(default='Immunity, Vitamins, Prevention, Clinical', max_length=255)),
                ('views_count', models.PositiveIntegerField(default=120)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.articlecategory')),
            ],
            options={
                'ordering': ['-is_featured', '-published_at'],
            },
        ),
    ]
